apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  annotations:
    networking.gke.io/load-balancer-type: "External"
  labels:
    app: demo-app
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
